export function createSeed() {
  return {
    nextProductId: 10,
    nextOrderId: 1,
    products: [
      {
        id: 1,
        name: 'Manilla Ojo Turco Nácar',
        category: 'Manillas',
        price: 29.9,
        stock: 12,
        image: 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=800&q=85',
        description: 'Manilla artesanal de cuentas delicadas con amuleto de ojo turco.',
      },
      {
        id: 2,
        name: 'Collar Perla Serena',
        category: 'Collares',
        price: 45,
        stock: 8,
        image: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=800&q=85',
        description: 'Collar de inspiración clásica con acabado nacarado y detalles dorados.',
      },
      {
        id: 3,
        name: 'Aretes Aurora',
        category: 'Aretes',
        price: 24.5,
        stock: 14,
        image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=85',
        description: 'Aretes ligeros con brillo sutil para cada día.',
      },
      {
        id: 4,
        name: 'Anillo Rosa Dorada',
        category: 'Anillos',
        price: 39,
        stock: 7,
        image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=85',
        description: 'Anillo de tono rosa dorado con una silueta elegante.',
      },
      {
        id: 5,
        name: 'Manilla Cristal Esmeralda',
        category: 'Manillas',
        price: 32,
        stock: 10,
        image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=800&q=85',
        description: 'Cristales verdes y cuentas artesanales en una pieza versátil.',
      },
      {
        id: 6,
        name: 'Collar Luz de Luna',
        category: 'Collares',
        price: 52,
        stock: 9,
        image: 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?auto=format&fit=crop&w=800&q=85',
        description: 'Colgante delicado para regalar o completar tu colección.',
      },
      {
        id: 7,
        name: 'Pulsera Brisa Marina',
        category: 'Manillas',
        price: 34.5,
        stock: 11,
        image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=85',
        description: 'Pulsera de tonos azules con cuentas delicadas inspiradas en el mar.',
      },
      {
        id: 8,
        name: 'Collar Sol de Nácar',
        category: 'Collares',
        price: 58,
        stock: 6,
        image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=85',
        description: 'Cadena fina con un colgante nacarado para ocasiones especiales.',
      },
      {
        id: 9,
        name: 'Aretes Jardín Dorado',
        category: 'Aretes',
        price: 27,
        stock: 13,
        image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=85',
        description: 'Aretes ligeros en tono dorado con un diseño floral discreto.',
      },
    ],
    deliverySettings: {
      zones: [
        { id: 1, name: 'Zona Norte / Centro Comercial' },
        { id: 2, name: 'Zona Sur / Calacoto / San Miguel' },
        { id: 3, name: 'Casco Viejo / Centro de la Ciudad' },
        { id: 4, name: 'Tienda Principal Belilo' },
      ],
      times: ['Mañana (09:00 - 12:00)', 'Tarde (14:00 - 17:00)', 'Noche (18:00 - 20:00)'],
      whatsappNumbers: ['70000000'],
    },
    orders: [],
  };
}
